### PR TITLE
y291ge support

### PR DESCRIPTION
**Pull request by lexxnsk**
I've grepped y291ga and added y291ge everywhere.
Please, review my changes and merge, if it is ok.
Thanks

### CODE REVIEW

**Comment by roleoroleo** [comment]
Is the fw version 9.0.35?
With the changes you made, does RTSP work?

**Comment by lexxnsk** [comment]
I don't have camera in my hands yet. 
I will receive it in a week and test

**Comment by lexxnsk** [comment]
No no. It is a simple monitoring cam.
I bought it here. https://pl.aliexpress.com/item/32815525549.html
Waiting for delivery.

**Comment by roleoroleo** [comment]
News about this cam?

**Comment by roleoroleo** [comment]
Closed.
Probably a y291ga.

**Pull request closed without merging**
