### PR TITLE
Allow set preset and fix go to preset

### PR DESCRIPTION
**Pull request by duhow**
Since the `set_preset` function is currently implemented in `ipc_cmd`, I'm adding it to the Web-UI.

- Fix Web-UI "Goto Preset" not working
- Add Web-UI "Set Preset" button + API `POST /preset.sh`
- Add Home Assistant (MQTT) Camera Preset (not persistent)

### CODE REVIEW

**Comment by duhow** [comment]
Still need to test locally before merging.... Fighting with compile process.

**Comment by duhow** [comment]
web tested!

**Comment by roleoroleo** [comment]
The preset implementation contained in ipc_cmd is not complete.
Because there are some problems:
- you can add a preset but only in the first unused position (8 positions available), you can't choose the index where to save it;
- you can't remove a preset at the moment (but it's possible adding a new command in ipc_cmd);
- you can't see the list of saved presets;
- the preview is available only inside the app, we should add a sort of label to identify the preset.

Do you think it's enough to make the feature usable?

**Comment by roleoroleo** [comment]
I will merge this pr and I will add the missing part (mainly ipc_cmd).
Thank you for your code.

**Comment by roleoroleo** [comment]
Do you want to update mqtt part after my last commits?
https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/94ec021e46bf8a726803b7be4b0c9675ac651182
https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/69d947fa654e8a30f75643254142578a10b77e8d

**Comment by duhow** [comment]
Sorry for the delay,

For what I tested I thought this was overriding the "last selected preset", but it appears to be appending to last preset as you mention.

Having labels for presets might need to have Yi-Hack to store and manage the preset references, so I'd leave that up to you on how to better handle it.

Sure, I can provide the changes for MQTT :)

**Comment by roleoroleo** [comment]
The IPC command to add a preset doesn't accept arguments about where to store the preset.
Simply it checks if there is a free position (starting from index 0) and stores the the preset.
The IPC command to delete a preset accepts "index" argument. And when you delete a preset the other presets are not reordered, the gap remains.

> Having labels for presets might need to have Yi-Hack to store and manage the preset references, so I'd leave that up to you on how to better handle it.

This is the hard part. The app stores a snapshot of the preset so you can recognize it. The hack cannot read the snapshot because it's not stored in the cam (I think).
And it's hard to read the preset storage because the struct depends on the cam model (y21ga, h51ga, etc...)

So, this is my thought:
- The preset editing must be done only with the hack. If you edit them from the app, hack and app will lose synchronism. You can use presets with the app but not add/delete.
- How to recognize presets? I think a label is enough, but it's stored in a different file: the preset is stored in the yi original struct using IPC commands, the label is stored in a file.

**Pull request merged**
