### PR TITLE
Add micropython for running python programs

### PR DESCRIPTION
**Pull request by krakowski**
Hi,

this PR adds [micropython](https://github.com/micropython/micropython) to the sources, enabling the execution of python scripts on the yi camera.

After https://github.com/roleoroleo/yi-hack-Allwinner-v2/pull/461 is merged, a small python program could be used to receive messages (via the `ffi` module) in a loop, instead of having `ipc_notify` spawn a new process for each message received.

### CODE REVIEW

**Comment by krakowski** [comment]
I just wrote a simple python program which receives a message from the `ipc_dispatch` queue, which works great!

```python
#!/tmp/sd/yi-hack/bin/python3

import ffi

# Constants
O_RDWR     = 0x0002
O_CREAT    = 0x0200
O_NONBLOCK = 0x0004
BUF_SIZE   = 512
QUEUE_NAME = "/ipc_dispatch"

# Open standard library
libc = ffi.open("libc.so.6")

# Lookup mq_open and mq_receive functions
mq_open    = libc.func("p", "mq_open",    "si")
mq_receive = libc.func("i", "mq_receive", "isip")

# Call mq_open on /ipc_dispatch queue
queue = mq_open(QUEUE_NAME, O_RDWR)

# Receive one message
buf = bytearray(BUF_SIZE)
mq_receive(queue, buf, BUF_SIZE, None)
print(''.join('{:02x}'.format(byte) for byte in buf))
```

I think this opens many new possibilities regarding plugins. Looking forward to feedback and ideas :slightly_smiling_face:

**Comment by roleoroleo** [comment]
I think you have forgotten a redirection in the file system.sh

About micropython compilation I have a couple of question:

1. The build process cannot find ffi.h. Probably you have this include in the host and it works but in my case I have to add CFLAGS in compile.micropython:
`export CFLAGS_MOD=-I(PATH_TO_ffi.h)`
2. I also have a linker problem. I need to chagne LD_FLAGS_MOD to
export LDFLAGS_MOD="-L${SCRIPT_DIR}/libffi/_install/lib -lffi"
3. The last section of compile.micropython:
```
# Copy upip package manager for micropython
#mkdir -p "${SCRIPT_DIR}/_install/.micropython/lib" || exit 1
cp ./build-standard/frozen_mpy/upip.mpy "${SCRIPT_DIR}/_install/.micropython/lib" || exit 1
cp ./build-standard/frozen_mpy/upip_utarfile.mpy "${SCRIPT_DIR}/_install/.micropython/lib" || exit 1
```
doesn't work for me, the path doesn't exist.

Could you please check these problems?

**Comment by krakowski** [comment]
Hi @roleoroleo,

> I think you have forgotten a redirection in the file system.sh

Do you get errors on startup?
 
> About micropython compilation I have a couple of question:
> 
> 1. The build process cannot find ffi.h. Probably you have this include in the host and it works but in my case I have to add CFLAGS in compile.micropython:
>    `export CFLAGS_MOD=-I(PATH_TO_ffi.h)`
> 2. I also have a linker problem. I need to chagne LD_FLAGS_MOD to
>    export LDFLAGS_MOD="-L${SCRIPT_DIR}/libffi/_install/lib -lffi"

You are right, I accidentaly installed libffi inside the dev container and didn't notice that the compiler used the host's header file. This should be fixed now :slightly_smiling_face: 

> 3. The last section of compile.micropython:
> 
> ```
> # Copy upip package manager for micropython
> #mkdir -p "${SCRIPT_DIR}/_install/.micropython/lib" || exit 1
> cp ./build-standard/frozen_mpy/upip.mpy "${SCRIPT_DIR}/_install/.micropython/lib" || exit 1
> cp ./build-standard/frozen_mpy/upip_utarfile.mpy "${SCRIPT_DIR}/_install/.micropython/lib" || exit 1
> ```
> 
> doesn't work for me, the path doesn't exist.

Just to be sure: Did you comment out the `mkdir` command by accident? Which path exactly does not exist?
I just rebuild the dev container (dropping any state it had before) and ran `init.micrypthon && compile.micropython` which works with the latest commit.

**Comment by roleoroleo** [comment]
> Do you get errors on startup?

No, simply /etc/profile is not filled:
`echo "PATH=/tmp/sd/yi-hack/bin:/tmp/sd/yi-hack/sbin:/tmp/sd/yi-hack/usr/bin:\$PATH"`

> Just to be sure: Did you comment out the `mkdir` command by accident?
Yes, sorry.

> Which path exactly does not exist?
> I just rebuild the dev container (dropping any state it had before) and ran `init.micrypthon && compile.micropython` which works with the latest commit.

./build-standard doesnt' exists
Inside `micropython-1.19/ports/unix` I have `variants` and `x86_64-pc-linux-gnu` folders.
Probably it depends on the host architecture.
I'm using a 64 bit debian.

**Comment by krakowski** [comment]
> No, simply /etc/profile is not filled: `echo "PATH=/tmp/sd/yi-hack/bin:/tmp/sd/yi-hack/sbin:/tmp/sd/yi-hack/usr/bin:\$PATH"`

Yes you are right. Seems I missed this line :sweat_smile: Fixed with https://github.com/roleoroleo/yi-hack-Allwinner-v2/pull/471/commits/8a5ce3952be63d742ddb0379f7688172408fc3c4

> ./build-standard doesnt' exists Inside `micropython-1.19/ports/unix` I have `variants` and `x86_64-pc-linux-gnu` folders. Probably it depends on the host architecture. I'm using a 64 bit debian.

It seems that the host's toolchain is picked up. I don't really know why this is happening. Did you

```
export STAGING_DIR="/opt/yi/toolchain-sunxi-musl"
export PATH="/opt/yi/toolchain-sunxi-musl/toolchain/bin:~/.local/bin:$PATH"
```

before running `init.micropython` and `compile.micropython`? The latest commit https://github.com/roleoroleo/yi-hack-Allwinner-v2/pull/471/commits/3b62f4bbe89ce97477a90655960e47a2145a1500 explicitly sets the variant name and the build output folder and uses absolute paths for copying the build files. Maybe this will work.

**Comment by roleoroleo** [comment]
The latest commit https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/3b62f4bbe89ce97477a90655960e47a2145a1500 fixed the problem of the folder.
The last problem I encountered is install.libffi, you need to add a "../":
```
mkdir -p ../../../build/yi-hack/bin/ || exit 1
rsync -av ./_install/* ../../../build/yi-hack/ || exit 1
```

**Comment by roleoroleo** [comment]
Ah no...
Another question.
The SD card is FAT32 formatted, so doesn't support symbolic links.
You should copy libffi.so.8.1.0 to libffi.so.8 and libffi.so

**Comment by krakowski** [comment]
https://github.com/roleoroleo/yi-hack-Allwinner-v2/pull/471/commits/c0a5902c9d006e5e221512a0eb764567f1166826 added the missing `../` in `install.libffi` and fixed the `cp` command in `compile.libffi` to use dereference mode, so that symbolic links are followed and the actual files are copied. I hope it works now :grin:

**Comment by roleoroleo** [comment]
Yes, it works properly.
Thank you for your contribution.

**Pull request merged**
